#!/bin/bash
argcount=4
usage="stdlib boot_device hostname cflags"
test "$#" -eq "${argcount}" || { echo "$0 ${usage}" && exit 1 ; }

#musl: http://distfiles.gentoo.org/experimental/amd64/musl/HOWTO

install_pkg()
{
        echo "entering install_pkg()" > /dev/stderr
        echo "install_pkg() got args: $@" > /dev/stderr
        #emerge --usepkgonly --tree -u --ask n -n "$@" > /dev/stderr || exit 1
        emerge --usepkg --tree -u --ask n -n "$@" > /dev/stderr || exit 1
}

emerge_world()
{
        echo "entering emerge_world()" > /dev/stderr
        #emerge --usepkgonly --tree -u --ask n -n "$@" > /dev/stderr || exit 1
        emerge --usepkg --tree -u --ask n -n world > /dev/stderr || exit 1
}

queue_emerge()
{
    echo "entering queue_emerge()" > /dev/stderr
        echo "adding ${@} to world"
        while [ $# -gt 0 ]
        do
            inpkg="${1}"
            pkg=`eix -e# "${inpkg}"`
            #emerge -puv "${pkg}"
            #emerge -puv "${pkg}" | grep "^\[ebuild" | grep "${pkg}"
            exit_status="$?"
            if [[ "${exit_status}" == 0 ]];
            then
                echo "adding to /var/lib/portage/world: ${pkg}"
                grep "${pkg}" /var/lib/portage/world > /dev/null 2>&1 || { echo "${pkg}" >> /var/lib/portage/world ; }
            fi
        shift
        done
}

stdlib="${1}"
shift
boot_device="${1}"
shift
hostname="${1}"
shift
cflags="${1}"
shift

timestamp=`date +%s`
echo "calling: source /etc/profile"
source /etc/profile
export PS1="(chroot) $PS1"
echo "setting passwd inside new chroot"
echo "root:cayenneground~__" | chpasswd

echo "chmod +x /home/cfg/sysskel/etc/local.d/*"
chmod +x /home/cfg/sysskel/etc/local.d/*
# right here, before layman is installed, before user is created, portage needs to get configured.
/home/cfg/setup/symlink_tree /home/cfg/sysskel/ || exit 1

echo "hostname=\"${hostname}\"" > /etc/conf.d/hostname

cores=`grep processor /proc/cpuinfo | wc -l`
echo "MAKEOPTS=\"-j${cores}\"" > /etc/portage/makeopts.conf

if [[ "${cflags}" == "native" ]];
then
    echo "CFLAGS=\"-march=native -O2 -pipe -fomit-frame-pointer -ggdb\"" > /etc/portage/cflags.conf
    echo "CXXFLAGS=\"\${CFLAGS}\"" >> /etc/portage/cflags.conf
elif [[ "${cflags}" == "nocona" ]]; # first x86_64 arch
then
    echo "CFLAGS=\"-march=nocona -O2 -pipe -fomit-frame-pointer -ggdb\"" > /etc/portage/cflags.conf
    echo "CXXFLAGS=\"\${CFLAGS}\"" >> /etc/portage/cflags.conf
else
    echo "Unknown cflags: ${cflags}"
    exit 1
fi

CFLAGS="-march=native -O2 -pipe -fomit-frame-pointer -ggdb"
#CFLAGS="-march=native -pipe -save-temps -Wformat-nonliteral -Wall -Wextra -O1 -ggdb -fbuiltin" #debug flags
CXXFLAGS="${CFLAGS}"



#if musl is getting used, CHOST must be changed
if [[ "${stdlib}" == "musl" ]];
then
    echo "setting CHOST to x86_64-gentoo-linux-musl"
    /home/cfg/_myapps/replace-text/replace-text 'CHOST="x86_64-pc-linux-gnu"' 'CHOST="x86_64-gentoo-linux-musl"' /etc/portage/make.conf
elif [[ "${stdlib}" == "uclibc" ]];
then
    echo "setting CHOST to x86_64-gentoo-linux-uclibc"
    /home/cfg/_myapps/replace-text/replace-text 'CHOST="x86_64-pc-linux-gnu"' 'CHOST="x86_64-gentoo-linux-uclibc"' /etc/portage/make.conf
elif [[ "${stdlib}" == "glibc" ]];
then
    echo -n "leaving CHOST as is: "
    grep x86_64-pc-linux-gnu /etc/portage/make.conf || { echo "x86_64-pc-linux-gnu not found in /etc/portage/make.conf, but glibc = ${glibc}, exiting." ; exit 1 ; }
else
    echo "unknown glibc: ${glibc}, exiting."
    exit 1
fi

echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen    #hm, musl does not need this? dont fail here for uclibc or musl
echo "LC_COLLATE=\"C\"" >> /etc/env.d/02collate
echo "US/Arizona" > /etc/timezone

#install kernel and update symlink (via use flag)
install_pkg hardened-sources || exit 1

#skip building kernel

mv /usr/src/linux/.config /usr/src/linux/.config.orig
ln -s /usr/src/linux_configs/.config /usr/src/linux/.config
#cp /usr/src/linux_configs/.config /usr/src/linux/.config
cores=`grep processor /proc/cpuinfo | wc -l`
#cd /usr/src/linux && make -j"${cores}" && make install && make modules_install || exit 1

# USE="${USE} -kernel-builtin" emerge spl zfs zfs-kmod || exit 1
# rc-update add zfs boot  #for zfs on root

env-update && source /etc/profile || exit 1

#echo '''GRUB_PLATFORMS="pc efi-32 efi-64"''' >> /etc/portage/make.conf #not sure why needed, but causes probls on musl
#echo '''GRUB_PLATFORMS="pc"''' >> /etc/portage/make.conf #not sure why needed, but causes probls on musl
install_pkg grub:2 || exit 1
install_pkg hexedit
#echo '''USE="$USE device-mapper"'''        >> /etc/portage/make.conf
root_partition=`/home/cfg/linux/disk/get_root_device`
echo "-------------- root_partition: ${root_partition} ---------------------"
#/bin/sh
partuuid=`/home/cfg/linux/hardware/disk/blkid/PARTUUID "${root_partition}"`
echo "GRUB_DEVICE partuuid: ${partuuid}"
#/bin/sh
echo "GRUB_DEVICE=\"PARTUUID=${partuuid}\"" >> /etc/default/grub
touch /etc/mtab

echo -e "#<fs>\t<mountpoint>\t<type>\t<opts>\t<dump/pass>" > /etc/fstab
echo -e 'PARTUUID='`/home/cfg/linux/disk/blkid/PARTUUID_root_device` '\t/' '\text4' '\tnoatime' '\t0' '\t1' >> /etc/fstab

#grub-install "${boot_device}" || exit 1

echo "grub-install --compress=no --target=i386-pc --boot-directory=/boot --recheck ${boot_device}"
grub-install --compress=no --target=i386-pc --boot-directory=/boot --recheck --no-rs-codes "${boot_device}" || exit 1
#/bin/sh

echo "grub-install --compress=no --target=x86_64-efi --efi-directory=/boot/efi --boot-directory=/boot"
grub-install --compress=no --target=x86_64-efi --efi-directory=/boot/efi --boot-directory=/boot --removable --recheck --no-rs-codes || exit 1
grub-mkconfig -o /boot/grub/grub.cfg || exit 1
#/bin/sh

test -d /boot/efi/EFI/BOOT || { mkdir /boot/efi/EFI/BOOT || exit 1 ; }
#cp -v /boot/efi/EFI/gentoo/grubx64.efi /boot/efi/EFI/BOOT/BOOTX64.EFI || exit 1 # grub does this via --removable

useradd --create-home user || exit 1
echo "user:cayenneground~__" | chpasswd || exit 1

test -h /home/user/cfg || { ln -s /home/cfg /home/user/cfg || exit 1 ; }
test -h /root/cfg      || { ln -s /home/cfg /root/cfg || exit 1 ; }

mkdir /usr/portage
#emerge-webrsync
#emerge --sync
eselect profile list

rmdir /etc/portage/package.mask

chmod +x /etc/local.d/export_cores.start
/etc/local.d/export_cores.start

mkdir /mnt/sda1 /mnt/sda2 /mnt/sda3
mkdir /mnt/sdb1 /mnt/sdb2 /mnt/sdb3
mkdir /mnt/sdc1 /mnt/sdc2 /mnt/sdc3
mkdir /mnt/sdd1 /mnt/sdd2 /mnt/sdd3
mkdir /mnt/sde1 /mnt/sde2 /mnt/sde3
mkdir /mnt/sdf1 /mnt/sdf2 /mnt/sdf3
mkdir /mnt/sdg1 /mnt/sdg2 /mnt/sdg3
mkdir /mnt/sdh1 /mnt/sdh2 /mnt/sdh3
mkdir /mnt/sdi1 /mnt/sdi2 /mnt/sdi3
mkdir /mnt/sdj1 /mnt/sdj2 /mnt/sdj3
mkdir /mnt/sdk1 /mnt/sdk2 /mnt/sdk3
mkdir /mnt/sdl1 /mnt/sdl2 /mnt/sdl3
mkdir /mnt/sdm1 /mnt/sdm2 /mnt/sdm3
mkdir /mnt/sdn1 /mnt/sdn2 /mnt/sdn3
mkdir /mnt/sdo1 /mnt/sdo2 /mnt/sdo3
mkdir /mnt/xvdi1 /mnt/xvdj1
mkdir /mnt/loop /mnt/samba /mnt/dvd /mnt/cdrom

eselect python set --python3 python3.4
eselect python set python3.4
eselect python list
eselect profile list

install_pkg ccache
install_pkg dev-vcs/git
mkdir /etc/portage/repos.conf #make this is layman is getting installed or not
#install_pkg net-misc/curl #only needed with custom FETCHCOMMAND

if [[ "${stdlib}" == "musl" ]];
then
    install_pkg layman   # pulls in git
    layman -L || exit 1  # get layman trees
    layman -a musl || exit 1
    echo "source /var/lib/layman/make.conf" >> /etc/portage/make.conf
fi

install_pkg sys-fs/eudev
touch /run/openrc/softlevel
/etc/init.d/udev --nodeps restart

if [[ "${stdlib}" == "musl" ]];
then
    emerge -puvNDq world
    emerge -puvNDq world --autounmask=n
    emerge -uvNDq world || exit 1 #http://distfiles.gentoo.org/experimental/amd64/musl/HOWTO
fi

rc-update add sshd default
rc-update del netmount default  #handeled later, dont want dhcpcd running all the time

install_pkg syslog-ng
rc-update add syslog-ng default

install_pkg dhcpcd
install_pkg cpio    #for better-initramfs

#fix ocaml and unison
#/bin/cp -v /home/cfg/setup/gentoo_installer/portage_overlay/ocaml/*.patch   /usr/portage/dev-lang/ocaml/files/
#/bin/cp -v /home/cfg/setup/gentoo_installer/portage_overlay/ocaml/*.ebuild  /usr/portage/dev-lang/ocaml/
#ebuild /usr/portage/dev-lang/ocaml/ocaml-4.02.3.ebuild manifest
#
#/bin/cp -v /home/cfg/setup/gentoo_installer/portage_overlay/unison/*.patch  /usr/portage/net-misc/unison/files/
#/bin/cp -v /home/cfg/setup/gentoo_installer/portage_overlay/unison/*.c  /usr/portage/net-misc/unison/files/ || exit 1
#/bin/cp -v /home/cfg/setup/gentoo_installer/portage_overlay/unison/*.ebuild /usr/portage/net-misc/unison/
#ebuild /usr/portage/net-misc/unison/unison-2.48.3.ebuild manifest
#
#/bin/cp -v /home/cfg/setup/gentoo_installer/portage_overlay/parted/*.patch  /usr/portage/sys-block/parted/files/
#/bin/cp -v /home/cfg/setup/gentoo_installer/portage_overlay/parted/*.ebuild /usr/portage/sys-block/parted/
#ebuild /usr/portage/sys-block/parted/parted-3.2.ebuild manifest
#
#mkdir /usr/portage/sys-apps/hwinfo/files/
#/bin/cp -v /home/cfg/setup/gentoo_installer/portage_overlay/hwinfo/*.patch  /usr/portage/sys-apps/hwinfo/files/
#/bin/cp -v /home/cfg/setup/gentoo_installer/portage_overlay/hwinfo/*.ebuild /usr/portage/sys-apps/hwinfo/
#ebuild /usr/portage/sys-apps/hwinfo/hwinfo-21.4.ebuild manifest
#
#mkdir /usr/portage/sys-apps/lshw/files/
#/bin/cp -v /home/cfg/setup/gentoo_installer/portage_overlay/lshw/*.patch  /usr/portage/sys-apps/lshw/files/
#/bin/cp -v /home/cfg/setup/gentoo_installer/portage_overlay/lshw/*.ebuild /usr/portage/sys-apps/lshw/
#ebuild /usr/portage/sys-apps/lshw/lshw-02.16b-r2.ebuild manifest

install_pkg unison
ln -s /usr/bin/unison-2.48 /usr/bin/unison


if [[ "${stdlib}" == "musl" ]];
then
    install_pkg argp-standalone #for musl
fi

install_pkg sys-process/time

install_pkg dnsmasq
mkdir /etc/dnsmasq.d
rc-update add dnsmasq default

install_pkg dnsproxy
rc-update add dnsproxy default

install_pkg gradm #required for gentoo-hardened RBAC

install_pkg eix #setup/linux:queue_emerge() needs this
eix-update

queue_emerge iw
queue_emerge linux-firmware
queue_emerge wpa_supplicant
queue_emerge htop
queue_emerge sudo
queue_emerge vim
queue_emerge pydf
queue_emerge click #python arg parser
queue_emerge requests
queue_emerge sys-apps/usbutils # for lsusb
queue_emerge psutil # python system info library
queue_emerge parted
queue_emerge multipath-tools # unhappy on musl
queue_emerge cryptsetup
queue_emerge pyparted
queue_emerge hexedit
queue_emerge ncdu
queue_emerge app-text/tree
queue_emerge dosfstools #mkfs.vfat for uefi partition
queue_emerge pv
queue_emerge app-crypt/gnupg
queue_emerge dev-util/dirdiff
queue_emerge tmux
queue_emerge gentoolkit
queue_emerge tcpdump
queue_emerge smartmontools   #to get HD sn's
queue_emerge gentoolkit       #equery
queue_emerge timer_entropyd  #ssh-keygen
queue_emerge hwinfo  # for checking avail kms modes and detecting video cards
queue_emerge lshw    # fixed for musl
queue_emerge pfl     # e-file like qpkg for files that are in portage
queue_emerge patchutils # combinediff
queue_emerge libbsd # strlcpy https://en.wikibooks.org/wiki/C_Programming/C_Reference/nonstandard/strlcpy
queue_emerge lsof
queue_emerge iotop
queue_emerge debugedit
queue_emerge gptfdisk #gdisk sgdisk cgdisk
queue_emerge gpart # partition disaster recovery tool
queue_emerge app-misc/mc
queue_emerge ddrescue
queue_emerge dd-rescue
queue_emerge python-gnupg
queue_emerge vbindiff
queue_emerge libisoburn # xorriso
queue_emerge expect # to script gdisk
emerge_world

/home/cfg/_myapps/replace-text/replace-text "c1:12345:respawn:/sbin/agetty 38400 tty1 linux" "c1:12345:respawn:/sbin/agetty 38400 tty1 linux --noclear" /etc/inittab || exit 1

echo "vm.overcommit_memory=2"   >> /etc/sysctl.conf
echo "vm.overcommit_ratio=100"  >> /etc/sysctl.conf
mkdir /sys/fs/cgroup/memory/0
#echo -e '''#!/bin/sh\necho 1 > /sys/fs/cgroup/memory/0/memory.oom_control''' > /etc/local.d/memory.oom_control.start #done in sysskel
#chmod +x /etc/local.d/memory.oom_control.start

install_pkg gpm
rc-update add gpm default   #console mouse support

install_pkg alsa-utils #alsamixer
rc-update add alsasound boot

# /home/cfg/setup/gentoo_installer/gentoo_setup_post_chroot_build_initramfs

#test -e /boot/grub/grub.cfg && mv /boot/grub/grub.cfg /boot/grub/grub.cfg."${timestamp}"
#cp /home/cfg/setup/gentoo_installer/grub.cfg /boot/grub/grub.cfg || echo "unable to copy grub.cfg!"

if [[ -d '/usr/src/linux/.git' ]];
then
    kernel_version=`git -C /usr/src/linux describe --always --tag`
else
    kernel_version=`readlink -f /usr/src/linux | cut -d '/' -f4 | cut -d '-' -f 2-`
fi

test -e /boot/vmlinuz && { echo "removing old vmlinuz symlink" ; rm /boot/vmlinuz ; }

ls -al /boot/vmlinuz-"${kernel_version}"
ln -s -r /boot/vmlinuz-"${kernel_version}" /boot/vmlinuz

#chown -R user:user /home/user
#chmod -R u+rw /home/user
chown root:root /etc/sudoers

for x in cdrom cdrw usb audio wheel; do gpasswd -a user $x ; done

mkdir /root/repos
cd /root/repos
git clone https://github.com/mrichar1/clipster.git
cd clipster
python setup.py install

#git clone https://github.com/jakeogh/replace-text.git
#chmod +x /root/repos/replace-text/replace-text
#popd




