[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sendgentoo"
version = "1!0.0.1787634131"
description = "Install Gentoo Linux"
authors = [
    { name = "Justin Keogh", email = "github.com@v6y.net" },
]
dependencies = [
    "click",
    "humanfriendly",
    "psutil",
    "asserttool @ git+https://github.com/jakeogh/asserttool@4bd23a06c2161e488415acde89c29537e6720cc1",
    "boottool @ git+https://github.com/jakeogh/boottool@de0bfdc8c77ee98c28f94c8fd470480964ac9cd1",
    "click-auto-help @ git+https://github.com/jakeogh/click-auto-help@c53f57c78529a51ae9b03f579d7ee6f2d63ca03a",
    "clicktool @ git+https://github.com/jakeogh/clicktool@4bc98af7590652693aef664af7485acde40688c2",
    "devicetool @ git+https://github.com/jakeogh/devicetool@d090c813cb524e3b565c759067b1d4af0536670d",
    "eprint @ git+https://github.com/jakeogh/eprint@6ee1deca0c24b684eb5093247d6bd22e11f1b057",
    "hs @ git+https://github.com/jakeogh/hs@b33c88f35cd24e773fea6ca4758193c9e815536d",
    "mounttool @ git+https://github.com/jakeogh/mounttool@1dc451c21a89a45ffb69161a6ed7432c8192d9a6",
    "sendgentoo-chroot @ git+https://github.com/jakeogh/sendgentoo-chroot@ffaff44642a90413eab847b59b675c9ae2ea4c83",
    "sendgentoo-deploy @ git+https://github.com/jakeogh/sendgentoo-deploy@d7b62541eb2cc43fec92c4f28047ccd2e0a0a4ad",
    "sendgentoo-stage @ git+https://github.com/jakeogh/sendgentoo-stage@fc8d314b0c5ec449113d45c33de3c3dd4ce9087d",
    "warntool @ git+https://github.com/jakeogh/warntool@c61bf0caba8dbbcec97662734f45b77bb59a5c95",
    "zfstool @ git+https://github.com/jakeogh/zfstool@ceb3f373cdea0694f21330a67362a7240138e56f",
]
license = "MIT"
requires-python = ">=3.12"

[project.urls]
Homepage = "https://github.com/jakeogh/sendgentoo"

[project.scripts]
sendgentoo = "sendgentoo.sendgentoo:sendgentoo"
sendgentoosimple = "sendgentoo.sendgentoosimple:sendgentoosimple"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "tests",
]

[tool.setuptools.package-data]
sendgentoo = [
    "py.typed",
]
