[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sendgentoo"
version = "1!0.0.1789047796"
description = "Install Gentoo Linux"
authors = [
    { name = "Justin Keogh", email = "github.com@v6y.net" },
]
dependencies = [
    "click",
    "humanfriendly",
    "psutil",
    "asserttool @ git+https://github.com/jakeogh/asserttool@4bd23a06c2161e488415acde89c29537e6720cc1",
    "boottool @ git+https://github.com/jakeogh/boottool@b57b7962c36db49cd67539286942970eb87a3104",
    "click-auto-help @ git+https://github.com/jakeogh/click-auto-help@0308bf2e30095ce9c87a083e1f013731827e60aa",
    "clicktool @ git+https://github.com/jakeogh/clicktool@4bc98af7590652693aef664af7485acde40688c2",
    "devicetool @ git+https://github.com/jakeogh/devicetool@9aa2e3e84b20dceabf4dfbbd3f6c906cd57f33d6",
    "eprint @ git+https://github.com/jakeogh/eprint@6ee1deca0c24b684eb5093247d6bd22e11f1b057",
    "hs @ git+https://github.com/jakeogh/hs@b33c88f35cd24e773fea6ca4758193c9e815536d",
    "mounttool @ git+https://github.com/jakeogh/mounttool@1dc451c21a89a45ffb69161a6ed7432c8192d9a6",
    "sendgentoo-chroot @ git+https://github.com/jakeogh/sendgentoo-chroot@18714e25b5e86fe54048985ba1909ee98800a943",
    "sendgentoo-deploy @ git+https://github.com/jakeogh/sendgentoo-deploy@c57b96a03b538be68d38c0a65d0ab9c95c3e8b98",
    "sendgentoo-stage @ git+https://github.com/jakeogh/sendgentoo-stage@4dd3d28a52fba3c2c001def901231164f8bd7762",
    "warntool @ git+https://github.com/jakeogh/warntool@c61bf0caba8dbbcec97662734f45b77bb59a5c95",
    "zfstool @ git+https://github.com/jakeogh/zfstool@008639730c3b5cfdee66c26964a474cedf728351",
]
license = "MIT"
requires-python = ">=3.12"

[project.urls]
Homepage = "https://github.com/jakeogh/sendgentoo"

[project.scripts]
sendgentoo = "sendgentoo.sendgentoo:sendgentoo"
sendgentoosimple = "sendgentoo.sendgentoosimple:sendgentoosimple"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
exclude = [
    "tests",
]

[tool.setuptools.package-data]
sendgentoo = [
    "py.typed",
]
